# Generated by Django 5.0.1 on 2024-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='skin cancer/images')),
            ],
        ),
    ]
