# Generated by Django 5.0.1 on 2024-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincancer',
            name='image',
            field=models.ImageField(upload_to='skin cancer/images/2024/2/18'),
        ),
    ]
