# Generated by Django 5.0.1 on 2024-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_virusc_alter_skincancer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virusc',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='alb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='alp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='alt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='ast',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='bil',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='che',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='chol',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='crea',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='ggt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='virusc',
            name='prot',
            field=models.FloatField(),
        ),
    ]
