# Generated by Django 5.0.1 on 2024-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_virusc_age_alter_virusc_alb_alter_virusc_alp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virusc',
            old_name='Sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='image',
            field=models.ImageField(upload_to='skin cancer/images/2024/2/23'),
        ),
    ]
