# Generated by Django 5.0.1 on 2024-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_skincancer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMOKING', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('YELLOW_FINGERS', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('ANXIETY', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('PEER_PRESSURE', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('CHRONIC_DISEASE', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('FATIGUE', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('ALLERGY', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('WHEEZING', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('ALCOHOL_CONSUMING', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('COUGHING', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('SHORTNESS_OF_BREATH', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('SWALLOWING_DIFFICULTY', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('CHEST_PAIN', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='image',
            field=models.ImageField(upload_to='skin cancer/images/2024/3/26'),
        ),
    ]
