# Generated by Django 5.0.1 on 2024-02-16 18:14

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('rating', models.PositiveIntegerField(default=0, help_text='Enter a doctor rating', validators=[dashboard.models.validate_positive_integer, dashboard.models.validate_max_value])),
                ('cellphone', models.CharField(max_length=15)),
                ('doctor_image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='doctor_images/')),
                ('address', models.TextField()),
            ],
        ),
    ]
