# Generated by Django 5.0.1 on 2024-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='doctor_images/'),
        ),
    ]
