# Generated by Django 5.0.1 on 2024-03-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_doctors_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
