# Generated by Django 5.0.1 on 2024-03-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usermessage'),
        ('userProfile', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.profile'),
        ),
    ]
