# Generated by Django 5.0.1 on 2024-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_doctors_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_image',
            field=models.ImageField(blank=True, default=models.ImageField(default='default.jpg', upload_to='profile_pics/'), upload_to=''),
        ),
    ]
