# Generated by Django 5.0.1 on 2024-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_doctors_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
    ]
