# Generated by Django 5.0.1 on 2024-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile_age_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='D_username', max_length=30),
            preserve_default=False,
        ),
    ]
